package WIX1002.Tutorials.Tutorial_1;

import java.util.Random;

// Print the minimum number from 10 random numbers generated by computer.
public class Q6 {
    public static void main(String[] args) {

        // Store the minimum number
        int minimumNumber = 10;

        for (int i = 0; i < 10; i++) {
            // Generate random number
            Random random = new Random();
            int number = random.nextInt(0, 10);

            System.err.print(number + ", ");

            // Check is number less than minimum number
            if (number < minimumNumber) {
                minimumNumber = number;
            }
        }

        System.err.println("\nThe minimum number generated by computer is " + minimumNumber);
    }
}
