package tutorial.tutorial_1;

import java.util.Random;
import java.util.Scanner;

// Guess a random number generated by computer.
public class Q12 {
    public static void main(String[] args) {
        Random random = new Random();

        int generatedNumber = random.nextInt(0, 10);

        // Given gusess trial
        int k = 5;
        int i;

        System.out.println("Choose a number between 1 to 100." + "Guess the number within 5 trials.");
        for (i = 0; i < 5; i++) {

            System.out.print("Guess the number: ");
            Scanner sc = new Scanner(System.in);
            int guessNumber = sc.nextInt();

            if (guessNumber == generatedNumber) {
                System.out.println("Congratulations!" + " You guessed the number.");
                break;
            } else if (generatedNumber < guessNumber && i != k - 1) {
                System.out.println("The number is" + " less than " + guessNumber);
                System.out.println("Try again." + "\n");
            } else if (generatedNumber > guessNumber && i != k - 1) {
                System.out.println("The number is" + " more than " + guessNumber);
                System.out.println("Try again." + "\n");

            }

            sc.close();
        }

        if (i == k) {
            System.out.println("You have exhausted" + " 5 trials.");
            System.out.println("The number was " + generatedNumber);
        }
    }
}
